import type { Metadata } from "next";
import "./globals.css";
import NavArea from "./_components/NavArea";
import TopArea from "./_components/TopArea";
import FooterArea from "./_components/FooterArea";
import HeaderArea from "./_components/HeaderArea";



export const metadata: Metadata = {
  title: "IIA Zimbabwe Conference",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased `}>
          <HeaderArea />
          {children}
          <FooterArea />
      </body>
    </html>
  );
}
