import type { Metadata } from "next";
import "./globals.css";
import FooterArea from "./_components/FooterArea";
import HeaderArea from "./_components/HeaderArea";
/* ToastContainer */
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


export const metadata: Metadata = {
  title: "IIA Zimbabwe Conference",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased `}>
          <HeaderArea />
          {children}
          <FooterArea />
          <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="colored" 
            />
      </body>
    </html>
  );
}
